spring:
  r2dbc:
    url: r2dbc:h2:mem:///test
    username: sa
    password:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
debug: true
