
eureka:
    instance:
        prefer-ip-address: true
        ip-address: 54.234.89.245
        non-secure-port: 10831
    client:
        service-url:
            defaultZone: http://ip-172-31-83-143.ec2.internal:8761/eureka
        register-with-eureka: true
        fetch-registry: true

r2dbc:
    host: 34.235.128.109
    user: pangtudy
    password: Dnjs960131!
    database: conference