
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: conference-api

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
debug: true
server:
  port: 10831
