spring:
  application:
    name: conference-api

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG

debug: true
server:
  port: 10831

---
spring:
  profiles:
    active: local

---
spring:
  profiles:
    active: dev

---
spring:
  profiles:
    active: stg
